config/routes.rb
Rails.application.routes.draw do
  resources :schemes do
    get :top, on: :collection
  end

   root "schemes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/scheme.rb
class Scheme < ApplicationRecord
validates :name, :address, :rating, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schemes_controller.rb
class SchemesController < ApplicationController
  before_action :set_scheme, only: %i[ show edit update destroy ]

  # GET /schemes
  def index
    @schemes = Scheme.all
  end

def top
  @schemes = Scheme.where(rating: 5)

end


  # GET /schemes/1
  def show
  end

  # GET /schemes/new
  def new
    @scheme = Scheme.new
  end

  # GET /schemes/1/edit
  def edit
  end

  # POST /schemes
  def create
    @scheme = Scheme.new(scheme_params)

    if @scheme.save
      redirect_to @scheme, notice: "Scheme was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /schemes/1
  def update
    if @scheme.update(scheme_params)
      redirect_to @scheme, notice: "Scheme was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /schemes/1
  def destroy
    @scheme.destroy
    redirect_to schemes_url, notice: "Scheme was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scheme
      @scheme = Scheme.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def scheme_params
      params.require(:scheme).permit(:name, :address, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schemes_helper.rb
module SchemesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Television</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class= "container" >
  
    <%= yield %>

    </div>
  </body>
</html>

app/views/schemes/_form.html.erb
<%= simple_form_for(@scheme) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :rating %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/schemes/_scheme.html.erb
<div id="<%= dom_id scheme %>">
  <p>
    <strong>Name:</strong>
    <%= scheme.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= scheme.address %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= scheme.rating %>
  </p>

</div>

app/views/schemes/edit.html.erb
<h1>Editing scheme</h1>

<%= render "form", scheme: @scheme %>

<br>

<div>
  <%= link_to "Show this scheme", @scheme %> |
  <%= link_to "Back to schemes", schemes_path %>
</div>

app/views/schemes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Schemes</h1>

<div id="schemes">
  <% @schemes.each do |scheme| %>
    <%= render scheme %>
    <p>
      <%= link_to "Show this scheme", scheme %>
    </p>
  <% end %>
</div>

<%= link_to "New schemees toop", new_scheme_path %>

app/views/schemes/new.html.erb
<h1>New scheme</h1>

<%= render "form", scheme: @scheme %>

<br>

<div>
  <%= link_to "Back to schemes", schemes_path %>
</div>

app/views/schemes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @scheme %>

<div>
  <%= link_to "Edit this scheme", edit_scheme_path(@scheme) %> |
  <%= link_to "Back to schemes", schemes_path %>

  <%= button_to "Destroy this scheme", @scheme, method: :delete %>
</div>

app/views/schemes/top.html.erb
<p style="color: green"><%= notice %></p>

<h1>TOP Schemes</h1>

<div id="schemes">
  <% @schemes.each do |scheme| %>
    <%= render scheme %>
    <p>
      <%= link_to "Show this scheme", scheme %>
    </p>
  <% end %>
</div>